version: '3.4'

services:
  filedb:
    container_name: filedb
    hostname: filedb
    networks:
      - test
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: "SqAdmin123!!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1435:1433"
    volumes:
      - filedata:/var/opt/mssql

  identitydb:
    container_name: identitydb
    hostname: identitydb
    networks:
      - test
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: "SqAdmin123!!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1434:1433"
    volumes:
      - userdata:/var/opt/mssql

  projectstore.identity:
    networks:
      - test
    image: ${DOCKER_REGISTRY-}projectstoreidentity
    build:
      context: .
      dockerfile: ProjectStore.Identity/Dockerfile
    depends_on:
      - identitydb
    ports:
      - "3430:8080"
      - "3431:8081"

  projectstore.fileservice:
    networks:
      - test
    image: ${DOCKER_REGISTRY-}projectstorefileservice
    depends_on:
    - filedb
    build:
      context: .
      dockerfile: ProjectStore/Dockerfile
    ports:
      - "2430:8080"
      - "2431:8081"

  projectstore.proxy:
    container_name: projectstore.proxy
    hostname: projectstore.proxy
    networks:
      - test
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - projectstore.identity
      - projectstore.fileservice
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw

volumes:
  userdata:
    external: true

networks:
  test:
    name: test
