version: '3.4'

services:
  identitydb:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: "SqAdmin123!!"
      ACCEPT_EULA: "Y"
      MSSQL_PID : "Developer"
    ports:
     - "1434:1433"
    volumes:
    - userdata:/var/opt/mssql
  projectstore.identity:
    image: ${DOCKER_REGISTRY-}projectstoreidentity
    build:
      context: .
      dockerfile: ProjectStore.Identity/Dockerfile
    depends_on:
      - identitydb
    ports:
    - "1432:80"

  projectstore.fileservice:
    image: ${DOCKER_REGISTRY-}projectstorefileservice
    build:
      context: .
      dockerfile: ProjectStore/Dockerfile
    ports:
    - "1431:80"
volumes:
  userdata:
    external: true

