version: '3.4'

services:
  identitydb:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: "SqAdmin123!!"
      ACCEPT_EULA: "Y"
      MSSQL_PID : "Developer"
    ports:
     - "1434:1433"
    volumes:
    - userdata:/var/opt/mssql
  projectstore.identity:
    image: ${DOCKER_REGISTRY-}projectstoreidentity
    build:
      context: .
      dockerfile: ProjectStore.Identity/Dockerfile
    depends_on:
      - identitydb
    ports:
    - "3430:8080"
    - "3431:8081"

  projectstore.fileservice:
    image: ${DOCKER_REGISTRY-}projectstorefileservice
    build:
      context: .
      dockerfile: ProjectStore/Dockerfile
    ports:
    - "2430:8080"
    - "2431:8081"
  projectstore.proxy:
    image: nginx
    ports:
    - "8080:8080"
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
volumes:
  userdata:
    external: true

